# Generated by Django 5.0 on 2023-12-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_category_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="color",
            field=models.CharField(
                choices=[
                    ("red", "Red"),
                    ("orange", "Orange"),
                    ("yellow", "Yellow"),
                    ("olive", "Olive"),
                    ("green", "Green"),
                    ("teal", "Teal"),
                    ("blue", "Blue"),
                    ("violet", "Violet"),
                    ("purple", "Purple"),
                    ("pink", "Pink"),
                    ("brown", "Brown"),
                    ("grey", "Grey"),
                    ("black", "Black"),
                ],
                default="celeste",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="create_at",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "DRAFT"),
                    ("published", "PUBLISHED"),
                    ("removed", "REMOVED"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="update_at",
            field=models.DateField(auto_now=True),
        ),
    ]
