# Generated by Django 5.0 on 2023-12-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_alter_category_color_alter_post_create_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=150),
        ),
    ]
