# Generated by Django 4.2.7 on 2023-12-12 23:11

from django.db import migrations, models
import django.db.models.deletion
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_comment_likes_count_post_likes_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="comment_post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="blog.post",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="update_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=martor.models.MartorField(),
        ),
        migrations.AlterField(
            model_name="postcategory",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="blog.category",
            ),
        ),
    ]
